use googletest::prelude::*;
use monja::MonjaProfileConfig;

use crate::sim::{Simulator, set_names};

#[allow(dead_code)]
#[macro_use]
mod sim;

// since testing this code requires an index file generated by a pull, basically all of these tests will pull first.
// we assume pull works based on the pull tests, so this isn't a particular issue.
// therefore, we won't do LocalValidation

// TODO: non-existing monjadir
// TODO: monjadir in ~/; will probably just change temp folder locations to nest repo in local, since this would be typical

#[gtest]
fn simple_set() -> Result<()> {
    let mut sim = Simulator::create();
    sim.configure_profile(|old| MonjaProfileConfig {
        target_sets: set_names(["simple"]),
        ..old
    });

    fs_operation! { SetManipulation, sim, "simple",
        dir "foo"
            dir "bar/baz"
                file "cake" "cake"
            end
        end
        dir "apple"
            file "pie" "pie"
            file "pasta" "pasta"
        end
        file "blueberry" "tart"
    };

    let _pull_result = monja::pull(&sim.profile())?;

    fs_operation! { LocalManipulation, sim,
        dir "apple"
            file "pie" "nopie"
            file "pasta" "nopasta"
        end
        file "newfile" "newfile"
    };

    let _push_result = monja::push(&sim.profile())?;

    fs_operation! { SetValidation, sim, "simple",
        dir "foo"
            dir "bar/baz"
                file "cake" "cake"
            end
        end
        dir "apple"
            file "pie" "nopie"
            file "pasta" "nopasta"
        end
        file "blueberry" "tart"
        // and no newfile, since not in index
    };

    Ok(())
}
